### ISSUE TITLE
Long code text not wrapping

### ISSUE THREAD

**Issue by torkelrogstad** [Dan-Smith-Suredbits/slate#5]
![image](https://user-images.githubusercontent.com/16610775/49998347-54568880-ff94-11e8-9a77-cfcc82907a87.png)

![image](https://user-images.githubusercontent.com/16610775/49998379-67695880-ff94-11e8-86d0-c407c9d06abc.png)

We should try and make the text wrap

**Comment by Dan-Smith-Suredbits** [comment]
It depends on screen width it seems.  The sample invoice shouldnt be doing that anymore. We changed that last release.   What device are you using?

The node is harder since we have to display the entire url.

**Comment by torkelrogstad** [comment]
Closed by #11
